create database VOTACION
go
USE VOTACION
GO
/**
TABLA USUARIO (CODIGOPK,EMAIL,CLAVE,NOMBRE,P_APELLIDO, S_APELLIDO)

TABLA CANDIDATOS (CODIGOPK,NOMBRECOMPLETO, NOMBREPARTIDO )

TABLA VOTANTES (IDCEDULA, NOMBRECOMPLETO,EMAIL)

TABLA VOTOS (CODIGOPK, IDCANDIDATO, IDVOTANTE)


TABLA RESULTADOS (IDRESULTADOPK,IDCANDIDATOFK,TOTAL VOTOS)

**/

CREATE TABLE USUARIO
(
ID INT IDENTITY (1,1) PRIMARY KEY,
EMAIL VARCHAR (50) UNIQUE NOT NULL,
CLAVE VARCHAR (30) NOT NULL,
NOMBRE VARCHAR (50) DEFAULT 'N/A',
P_APELLIDO VARCHAR (50) NOT NULL,
S_APELLIDO VARCHAR (50) NULL,

)
GO

CREATE TABLE CANDIDATOS 
(ID INT IDENTITY (1,1)PRIMARY KEY,
NOMBRECOMPLETO VARCHAR (60) NOT NULL, 
NOMBREPARTIDO VARCHAR (50) UNIQUE NOT NULL, 
)
GO

CREATE TABLE VOTANTES 
(
IDCEDULA VARCHAR (50) UNIQUE, 
NOMBRECOMPLETO VARCHAR (60) NOT NULL,
EMAIL VARCHAR (50)DEFAULT 'N/A',
)
GO

CREATE TABLE VOTOS 
(
IDVOTO INT IDENTITY (1,1), 
IDCANDIDATO VARCHAR(50)NOT NULL,  
IDVOTANTE VARCHAR (50) UNIQUE NULL
)
GO

CREATE TABLE RESULTADOS 
(
IDRESULTADO INT PRIMARY KEY,
IDCANDIDATO VARCHAR (50) UNIQUE NOT NULL,
TOTALVOTOS VARCHAR (1000) NOT NULL
)
GO

INSERT INTO USUARIO (EMAIL,CLAVE,NOMBRE, P_APELLIDO, S_APELLIDO) VALUES ('mario@tribunal.com', '123', 'Mario', 'Solis','Herrera'), ('rebeca@tribunal.com', '456', 'Rebeca', 'Castro', 'Artavia')

SELECT * FROM USUARIO
GO

INSERT INTO CANDIDATOS (NOMBRECOMPLETO, NOMBREPARTIDO) VALUES ('Jose Maria Figueres', 'PLN'), ('Rodrigo Chaves', 'Progreso Social'), ('Rafael Angel Calderon', 'PUSC'), ('Carlos Alvarado', 'Accion Ciudadana')
SELECT * FROM CANDIDATOS
GO

SELECT EMAIL, CLAVE, NOMBRE FROM USUARIO WHERE EMAIL='mario@tribunal.com' AND CLAVE='123'
select * from USUARIO
go
SELECT * FROM USUARIO
go
SELECT IDCANDIDATO, COUNT(*) AS TotalVotos
FROM VOTOS
GROUP BY IDCANDIDATO

SELECT c.NOMBRECOMPLETO, v.IDCANDIDATO, COUNT(*) AS TotalVotos
FROM VOTOS v
JOIN CANDIDATOS c ON v.IDCANDIDATO = c.ID
GROUP BY c.NOMBRECOMPLETO, v.IDCANDIDATO